Add examples how to allow browser access to Gnome extensions connector
netblue30/firejail pull request #4179
Opened 2021-04-10 18:24 UTC by jose1711

Fixes #4177.

2021-04-10 18:36 UTC, rusty-snake reviewed
:+1:

2021-04-10 18:36 UTC, rusty-snake commented on etc/profile-a-l/chromium-common.profile
> +#include allow-python3.inc
Move it up to line 14:

```
noblacklist ${HOME}/.local/share/pki

# Add the next line to your chromium-common.local if you want chromium-based browser
# to have access to Gnome extensions (extensions.gnome.org) via browser connector
#include allow-python3.inc

include disable-common.inc
```

2021-04-10 18:36 UTC, rusty-snake commented on etc/profile-a-l/firefox.profile
> +#include allow-python3.inc
Same, and I would just say "the next/following lines". Including a number means that if someone add a new line (e.g. `dbus-user.talk org.gnome.ChromeGnomeShell2`) this must be updated too to be correct.

2021-04-14 10:04 UTC, rusty-snake requested changes
#### chromium-common.profile

- Keep the accidental removed `#include chromium-common-hardened.inc.profile`
- FWIW: this common is used by all chromium based (e.g. brave or vivaldi).

#### firefox.profile

We have already a GNOME Shell integration snippet in firefox-common-addons.profile (which is the proper profile for that, if I think again):

https://github.com/netblue30/firejail/blob/83b95efe1a8f5b4386243a50d28065b14567faf3/etc/profile-a-l/firefox-common-addons.profile#L73-L79

So we can harden this one to keep the system-bus blocked and use filter instead of allow for the session-bus.

2021-04-14 23:04 UTC, jose1711 commented
> #### chromium-common.profile
> 
>     * Keep the accidental removed `#include chromium-common-hardened.inc.profile`

Oops, note taken down.

>     * FWIW: this common is used by all chromium based (e.g. brave or vivaldi).
> 
> 
> #### firefox.profile
> 
> We have already a GNOME Shell integration snippet in firefox-common-addons.profile (which is the proper profile for that, if I think again):
> 
> https://github.com/netblue30/firejail/blob/83b95efe1a8f5b4386243a50d28065b14567faf3/etc/profile-a-l/firefox-common-addons.profile#L73-L79

Hmm.. tested with `firefox-common-addons.profile` included but it stays broken for me. I had to add the following 3 lines to get rid of the errors:
```
dbus-user.talk org.gnome.ChromeGnomeShell
dbus-user.talk org.gnome.Shell
dbus-user.talk ca.desrt.dconf
```

Wonder if anyone else can confirm the same with (other than) Arch Linux too.


> 
> So we can harden this one to keep the system-bus blocked and use filter instead of allow for the session-bus.

2021-04-15 08:21 UTC, rusty-snake commented
> Hmm.. tested with firefox-common-addons.profile included but it stays broken for me. I had to add the following 3 lines to get rid of the errors:

Makes sense because firefox uses `dbus-user filter`. Maybe

```
# GNOME Shell integration (chrome-gnome-shell) needs dbus and python 
noblacklist ${HOME}/.local/share/gnome-shell 
whitelist ${HOME}/.local/share/gnome-shell 
dbus-user.talk ca.desrt.dconf
dbus-user.talk org.gnome.ChromeGnomeShell
dbus-user.talk org.gnome.Shell
# Allow python (blacklisted by disable-interpreters.inc) 
include allow-python3.inc 
```

2021-04-16 19:45 UTC, jose1711 commented
> ```
> # GNOME Shell integration (chrome-gnome-shell) needs dbus and python 
> noblacklist ${HOME}/.local/share/gnome-shell 
> whitelist ${HOME}/.local/share/gnome-shell 
> dbus-user.talk ca.desrt.dconf
> dbus-user.talk org.gnome.ChromeGnomeShell
> dbus-user.talk org.gnome.Shell
> # Allow python (blacklisted by disable-interpreters.inc) 
> include allow-python3.inc 
> ```

Worked for me, made adjustments and force-pushed now

2021-04-16 19:55 UTC, rusty-snake approved these changes

2021-04-16 20:49 UTC, glitsj16 commented
I haven't used chrome-gnome-shell in a while, but I recall it also used to show desktop notifications informing the user of update availability. If we allow GNOME Shell integration this way, shouldn't it make sense to add a filter for notifiers too, something like the below?
```
dbus-user.talk org.freedesktop.Notifications
dbus-user.talk org.kde.knotify
dbus-user.talk org.kde.StatusNotifierWatcher
```

2021-04-16 20:53 UTC, rusty-snake commented
> dbus-user.talk org.freedesktop.Notifications

Make sense if it's used.

> dbus-user.talk org.kde.knotify

Is this used? It's GNOME.

> dbus-user.talk org.kde.StatusNotifierWatcher

Tray icons are dead on GNOME.

2021-04-16 20:58 UTC, glitsj16 commented
> Is this used? It's GNOME.
    dbus-user.talk org.kde.StatusNotifierWatcher

Correct, my bad.

> Tray icons are dead on GNOME.

That's exactly why people who want them install GS extensions. Besides, there are other options for controlling GS extensions now in GNOME 40. And installing those via native package management tools is always going to be safer anyway IMO.

2021-04-17 08:45 UTC, jose1711 commented
> I haven't used chrome-gnome-shell in a while, but I recall it also used to show desktop notifications informing the user of update availability. If we allow GNOME Shell integration this way, shouldn't it make sense to add a filter for notifiers too, something like the below?
> 
> ```
> dbus-user.talk org.freedesktop.Notifications
> dbus-user.talk org.kde.knotify
> dbus-user.talk org.kde.StatusNotifierWatcher
> ```

No idea - I never enable browser notifications. Maybe someone who really needs them can comment and prepare another commit.

2021-04-24 09:46 UTC, merged

2021-04-24 09:46 UTC, rusty-snake commented
Merged, thanks.