Fix sndio support
netblue30/firejail pull request #4365
Opened 2021-06-19 23:20 UTC by lxeiqr

This patch allows sandboxed programs to access a sndiod server and play audio on systems where sndio handles audio.

2021-06-19 23:35 UTC, SkewedZeppelin requested changes
-1, don't add /tmp to this, will effectively apply private-tmp to all profiles using whitelist-common

2021-06-19 23:35 UTC, SkewedZeppelin commented
This is likely something you should add to your locals.

2021-06-20 05:21 UTC, rusty-snake requested changes
- [ ] Move it into the common block (the first one)
- [x] Only `whitelist` in `${HOME}` (if `whitelist /tmp/sndio` is necessary, we should add it to `private-tmp`)

2021-06-20 08:35 UTC, lxeiqr commented
>     * [ ]  Move it into the common block (the first one)
> 
>     * [ ]  Only `whitelist` in `${HOME}` (if `whitelist /tmp/sndio` is necessary, we should add it to `private-tmp`)
I've removed that last line and moved the cookie whitelist into the common block. However, I'm not quite sure how to handle the /tmp/sndio directory. Usually it contains UNIX domain sockets (e.g. /tmp/sndio/sndio0) used to connect to the server.

2021-06-20 09:56 UTC, rusty-snake commented on etc/inc/whitelist-common.inc
> +whitelist ${HOME}/.sndio/cookie
```suggestion
whitelist ${HOME}/.sndio/cookie
whitelist ${HOME}/.uim.d
```

2021-06-20 10:01 UTC, rusty-snake commented
> However, I'm not quite sure how to handle the /tmp/sndio directory. Usually it contains UNIX domain sockets (e.g. /tmp/sndio/sndio0) used to connect to the server.

I think a `profile_add("whitelist /tmp/sndio");` in `fs_private_tmp` works

https://github.com/netblue30/firejail/blob/447e30e2c9b24f4ec6af5520a37a77068e66383b/src/firejail/fs.c#L1251-L1299

2021-06-20 11:23 UTC, lxeiqr commented
> > However, I'm not quite sure how to handle the /tmp/sndio directory. Usually it contains UNIX domain sockets (e.g. /tmp/sndio/sndio0) used to connect to the server.
> 
> I think a `profile_add("whitelist /tmp/sndio");` in `fs_private_tmp` works
> 
> https://github.com/netblue30/firejail/blob/447e30e2c9b24f4ec6af5520a37a77068e66383b/src/firejail/fs.c#L1251-L1299

Done, now it works properly without any extra tweaking.

2021-06-20 11:23 UTC, lxeiqr commented
Done, now it works properly without any extra tweaking.

2021-06-20 13:20 UTC, rusty-snake reviewed
LGTM

2021-06-20 13:20 UTC, rusty-snake commented on src/firejail/fs.c
> +        profile_add("whitelist /tmp/sndio");
8 spaces -> 1 tab

2021-06-20 15:56 UTC, rusty-snake approved these changes

2021-07-01 12:36 UTC, merged

2021-07-01 12:37 UTC, netblue30 commented
Thanks for the patch!