Added quiet to some CLI profiles
netblue30/firejail pull request #4438
Opened 2021-08-03 14:45 UTC by caydey

"quiet" added to these profiles
- bleachbit
- img2txt
- keepassxc-cli
- ncdu
- pdftotext
- weechat

2021-08-03 14:52 UTC, rusty-snake reviewed
LGTM

2021-08-03 14:52 UTC, rusty-snake commented on etc/profile-m-z/ncdu.profile
> +quiet
Add `quiet`or `ignore quiet` to ncdu2.profile.

2021-08-03 14:52 UTC, rusty-snake commented on etc/profile-m-z/weechat.profile
> +quiet
Add `quiet`or `ignore quiet` to weechat-curses.profile.

2021-08-10 20:00 UTC, kmk3 requested changes
> [Merge branch 'netblue30:master' into master](https://github.com/netblue30/firejail/pull/4438/commits/2f6d71b7a570e9a142266eed1531c2dccc0dada1)

Please refrain from pulling changes from master after a PR is opened unless
they are substantial to the PR.  For example, when conflicts need to be
resolved or if a change impacts your PR.  A merge-based pull makes the history
more complicated and a rebase-based pull can make reviewing harder.

And if you are going to pull from master, in most cases it's better to do so
with rebase rather than merges (unless you have a very good reason to use
merges).  Example:

```sh
# ensure that there are no outstanding commits
git checkout mybranch
git push
# update master
git checkout master
git pull
# rebase to master
git checkout mybranch
git rebase master
```

With shortcuts:


```sh
# ensure that there are no outstanding commits
git checkout mybranch
git push
# update/rebase to master
git pull --rebase origin master
```

Since you're developing this direclty on your master branch:

```sh
# ensure that there are no outstanding commits
git push
# update/rebase to master
git pull --rebase netblue30 master
```

I'd suggest doing the above on this branch, as rebasing by default flattens the
merges/makes the history linear.

Also, I just noticed that this branch contains a duplicate commit from the
upstream master (from #4434):

Original:

* commit 242d5c764 ("Added ~/Private blacklist (`#4434`)")

Duplicate:

* commit 4bc847151 ("Added ~/Private blacklist")

This is one reason why each PR should be developed in its own separate topic
branch.  I'd advise to never commit directly on master unless you know enough
git to identify and prevent problems such as the above one.

2021-11-16 15:15 UTC, rusty-snake commented
@caydey

2021-11-23 13:43 UTC, netblue30 commented
Let's grab it as is, thanks @caydey for the patch! I'll clean up the rest of them.

2021-11-23 13:43 UTC, merged

2021-11-23 13:47 UTC, netblue30 commented
added quiet to ncdu2 and weechat-curses in the next commit.

2025-06-28 21:16 UTC, Lealed02 approved these changes