Fix shellcheck warnings
netblue30/firejail pull request #4574
Opened 2021-09-22 15:28 UTC by a1346054

Split from  #4497 for further discussion.

I did not modify the configure script, which is a source of a lot of the remaining shellcheck warnings, because it comes from autoconf and so it makes little sense to try to fix it here.

I also did not modify the scripts in contrib, because they possibly are maintained at some other place. Similarly with the other scripts that don't appear to be called from any of the makefiles.

2021-09-22 21:10 UTC, reinerh approved these changes

2021-09-22 21:21 UTC, kmk3 requested changes
NAK, as written in here:

https://github.com/netblue30/firejail/pull/4497#pullrequestreview-746590774

These changes produce a lot of noise, but the fixes are incomplete.

2021-10-14 00:54 UTC, a1346054 commented
That option has been checked since the start. I don't know why it is not working as it should.

2021-10-14 01:30 UTC, kmk3 commented
@a1346054 commented [on Oct 13](https://github.com/netblue30/firejail/pull/4574#issuecomment-942837250):

> That option has been checked since the start. I don't know why it is not
> working as it should.

I was trying to push the wrong branch actually, my bad.  Now it worked.

---

So, the new commits contain my (and @rusty-snake's) suggestions.

If you agree, you can squash them with something like:

```sh
git checkout shellcheck-fix
git rebase -i --autosquash "$(git merge-base master HEAD)"
```

Then, for the commit message of the main commit:

Suggestion: Change it to the following:

```
Fix some shellcheck warnings

Note: This does not modify the configure script, which is a source of a lot of
the remaining shellcheck warnings, because it comes from autoconf and so it
makes little sense to try to fix it here.

Also, it does not modify the scripts in contrib, because they possibly are
maintained at some other place. Similarly with the other scripts that don't
appear to be called from any of the makefiles.
```

It's taken from the first post, but adapted to be more in line with the
following:

* <https://chris.beams.io/posts/git-commit/>

This information helps understand the intent, as only some shell scripts are
changed and it is not clear from the current message which ones were considered
and why.

By the way, there are more shellcheck warnings on these files, but let's ignore
them for this PR, as: one doesn't make much sense (`$CONFIG_ARGS`), others I'm
not sure about (unused vars) and for one of them I already had a better
solution than the suggested fix anyway (redirects).

2021-10-30 22:39 UTC, kmk3 commented
@a1346054

Hello, any thoughts on the above suggestions?

I can do the changes and rebasing if you want.

2021-10-31 15:39 UTC, a1346054 commented
I should be able to look at this some more in 2 days.

2021-11-02 20:26 UTC, Fred-Barclay approved these changes

2021-11-03 23:41 UTC, a1346054 commented
I looked it over and all the suggested changes are fine. It's optional and possibly just a matter of taste whether the extra quotes are added or not, I don't have any hard feelings about it.

Feel free to reword the commit message and merge, I am away from the computer that has the required gpg key to make the change myself.

2021-11-05 02:59 UTC, kmk3 commented
@a1346054 commented [on Nov 3](https://github.com/netblue30/firejail/pull/4574#issuecomment-960297495):

> I looked it over and all the suggested changes are fine. It's optional and
> possibly just a matter of taste whether the extra quotes are added or not, I
> don't have any hard feelings about it.

I'll say that I was surprised when I noticed that shellcheck doesn't warn about
things like `USER=$(whoami)`, as I thought that assignments were also
susceptible to expansion pitfalls (and I think I've seen both versions being
used in different projects), but now I'm not sure if that's the case.  But
either way, I like the consistency of always quoting variables and command
expansions and I suppose that other people could be confused by the differing
behavior (and quoting usage) as well, so quoting assignments with expansions
may also help with clarity in that regard.

Misc: If anyone knows of a good explanation of why assignments behave
differently in this way, please let me know.

> Feel free to reword the commit message and merge, I am away from the computer
> that has the required gpg key to make the change myself.

Very well, I'll do the changes then.

2021-11-05 06:13 UTC, kmk3 commented on mkasc.sh
> +cd /transfer || exit
Done.

2021-11-05 06:13 UTC, kmk3 commented on mkdeb.sh.in
> +TOP=$(pwd)
Done.

2021-11-05 06:13 UTC, kmk3 approved these changes
LGTM.

2021-11-05 06:14 UTC, merged

2021-11-05 12:39 UTC, a1346054 commented
> Misc: If anyone knows of a good explanation of why assignments behave
> differently in this way, please let me know.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01 says "Each variable assignment shall be expanded for tilde expansion, parameter expansion, command substitution, arithmetic expansion, and quote removal prior to assigning the value." So field splitting is not done.

2021-11-05 20:50 UTC, kmk3 commented
@a1346054 commented [on Nov 5](https://github.com/netblue30/firejail/pull/4574#issuecomment-961863569):

> > Misc: If anyone knows of a good explanation of why assignments behave
> > differently in this way, please let me know.
> 
> https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01
> says "Each variable assignment shall be expanded for tilde expansion,
> parameter expansion, command substitution, arithmetic expansion, and quote
> removal prior to assigning the value." So field splitting is not done.

Thanks a lot!