Fix teams ignoring input sources e.g. microphones
netblue30/firejail pull request #4779
Opened 2021-12-14 19:07 UTC by seonwoolee

`teams-for-linux.profile` and `teams.profile` both include `electron.profile`, which has the `noinput` option, which blocks microphones and other input sources, so this option needs to be ignored.

2021-12-14 19:11 UTC, rusty-snake requested changes
Don't put them in the "Disabled until someone reported positive feedback" block.

---

Is this special for teams or does it also happen with e.g. firefox?

2021-12-14 19:15 UTC, seonwoolee commented
Sorry, I was trying to respect the ordering rules for pull requests.

It's not a general problem, just any electron app that needs microphone input. Not applicable to Firefox

2021-12-14 19:18 UTC, rusty-snake approved these changes

2021-12-14 19:34 UTC, kmk3 commented on etc/profile-m-z/teams.profile
> +ignore novideo
I think you meant `ignore noinput`.

2021-12-14 20:00 UTC, kmk3 commented
Also, could you squash the commits and push?  Example:

```sh
git stash; git tag backup # just in case
git rebase -i "$(git merge-base master HEAD)..HEAD"
# Change all occurrences of "pick" to "fixup", except for the first one
# (This makes the first commit "absorb" all the other commits)
# Check if it looks good (if not, `git reset --hard backup` and try again)
# Then just push
git push --force-with-lease
```

2021-12-18 15:28 UTC, merged

2021-12-18 15:28 UTC, netblue30 commented
merged, thanks!

2021-12-29 22:14 UTC, rusty-snake commented on etc/profile-m-z/teams.profile
> +ignore novideo
Still unresolved.