Add godot3 redirect
netblue30/firejail pull request #5456
Opened 2022-11-05 23:37 UTC by Frostbyte4664

The Ubuntu package for Godot and its executable are both called godot3. This pull request adds a redirect profile and enables it in firecfg.

2022-11-06 09:23 UTC, rusty-snake approved these changes

2022-11-06 09:24 UTC, rusty-snake requested changes

2022-11-06 09:24 UTC, rusty-snake commented on godot3.profile
> +include godot
```suggestion
include godot.profile
```

2022-11-06 09:35 UTC, rusty-snake commented
![Screenshot](https://user-images.githubusercontent.com/41237666/200161281-b6adfb32-e47e-414b-84ea-a2cd7c00b735.jpg)

I'm a time traveler <img src="https://user-images.githubusercontent.com/41237666/200161494-7213f14f-6846-4b60-806f-bf54b3b0d525.png" height="30" />

2022-11-06 10:47 UTC, rusty-snake approved these changes

2022-11-06 12:22 UTC, kmk3 requested changes
godot3.profile should be in the same directory as godot.profile.

2022-11-07 02:26 UTC, kmk3 approved these changes
LGTM.

2022-11-07 02:27 UTC, merged

2022-11-07 02:27 UTC, kmk3 commented
Merged, thanks!