add bsfilter to email profile
netblue30/firejail pull request #5718
Opened 2023-03-07 10:14 UTC by marek22k

If your PR isn't about profiles or you have no idea how to do one of these, skip the following and go ahead with this PR.

If you submit a PR for new profiles or changing profiles, please do the following:
 - The ordering of options follow the rules described in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).
   > Hint: The profile-template is very new. If you install firejail with your package manager, it may be missing. In order to follow the latest rules, it is recommended to use the template from the repository.
 - Order the arguments of options alphabetically. You can easily do this with [sort.py](https://github.com/netblue30/firejail/tree/master/contrib/sort.py).
 The path to it depends on your distro:

   | Distro | Path |
   | ------ | ---- |
   | Arch/Fedora | `/usr/lib64/firejail/sort.py` |
   | Debian/Ubuntu/Mint | `/usr/lib/x86_64-linux-gnu/firejail/sort.py` |
   | local git clone | `contrib/sort.py` |

   Note also that the sort.py script exists only since firejail `0.9.61`.

See also [CONTRIBUTING.md](/CONTRIBUTING.md).

2023-03-07 10:45 UTC, kmk3 reviewed
What is the project page for the program that creates this path?

For clarity, change the commit message title to the PR title and add the
project page to the commit message body.

Other than that, LGTM.

2023-03-07 10:49 UTC, marek22k commented
> What is the project page for the program that creates this path?

https://bsfilter.org/
https://duckduckgo.com/?t=ftsa&q=bsfilter+spam
https://directory.fsf.org/wiki/Bsfilter

2023-03-07 10:52 UTC, kmk3 approved these changes

2023-03-07 11:54 UTC, glitsj16 commented on etc/profile-a-l/email-common.profile
> +noblacklist ${HOME}/.bsfilter
A `noblacklist foo` only makes sense when there's a `blacklist foo`, like in the ${HOME}/.bogofilter case:

https://github.com/netblue30/firejail/blob/1f5f84f9596ba7d26c2f2e35dad7728e12afaec9/etc/inc/disable-programs.inc#L53

This protects the configuration from apps that don' need access to it.

Please add the needed `blacklist ${HOME}/.bsfilter` to `disable-programs.inc` (respecting sort order).

2023-03-07 11:55 UTC, glitsj16 requested changes
Add blacklist counterpart.

2023-03-08 11:18 UTC, glitsj16 approved these changes
LGTM

2023-03-08 16:24 UTC, netblue30 commented
merged, thanks!

2023-03-08 16:24 UTC, merged