softmaker-etc-fstab
netblue30/firejail pull request #5777
Opened 2023-04-03 20:37 UTC by hotcapy

While `private-etc` profile option is active, SoftMaker Office "forgets" that it was activated already & asks for product key again. Allowing access to `/etc/fstab` configuration file should fix the following error:

```
The application cannot create a unique identifier.
Please make sure the application has sufficient permissions.
```

Issue #5773.

2023-04-03 21:07 UTC, glitsj16 approved these changes
LGTM

2023-04-03 21:43 UTC, kmk3 requested changes
(There are a few suggestions but I can't review at the moment; leaving this as
a placeholder)

2023-04-05 13:23 UTC, kmk3 reviewed
(Sorry for the delay)

Change the commit message to something like the following:

```
softmaker-common.profile: add fstab to private-etc

When using `private-etc`, SoftMaker Office "forgets" that it was activated
already & asks for product key again.

Allowing access to "/etc/fstab" fixes the following error:

    The application cannot create a unique identifier.
    Please make sure the application has sufficient permissions.

Fixes #5773.
```

Main changes:

* Clarify in the title what the commit does
* Indent error message by 4 spaces
* Add "Fixes #XXX", which makes the issue be closed automatically when the PR
  is merged

See the following for details:

* <https://chris.beams.io/posts/git-commit/>

Amending the commit message can be done with:

```sh
# (change the commit locally)
git checkout patch-1
git commit --amend

# (check the result)
git show

# (change the commit remotely)
git push --force-with-lease
```

By the way, are you familiar with using git locally?

Knowing how to amend commits would be helpful for contributing in general, but
if this seems too much, I can do the fix.

2023-04-06 21:37 UTC, kmk3 commented on etc/profile-m-z/softmaker-common.profile
> +private-etc @tls-ca,SoftMaker,fstab
```suggestion
private-etc @tls-ca,fstab,SoftMaker
```

```console
$ ./contrib/sort.py etc/profile-m-z/softmaker-common.profile
sort.py: checking 1 profile(s)...
etc/profile-m-z/softmaker-common.profile:45:-private-etc @tls-ca,SoftMaker,fstab
etc/profile-m-z/softmaker-common.profile:45:+private-etc @tls-ca,fstab,SoftMaker
[ Fixed ] etc/profile-m-z/softmaker-common.profile
```

Sort as per sort.py.

2023-04-06 21:38 UTC, kmk3 commented
> hotcapy force-pushed the patch-1 branch from e747284 to 8fe750a 

The result looks good.

> Sort as per sort.py.

The commit can be amended with:

```sh
# (change the file manually)
# [...]

# (redo the commit with the new changes)
git add -u
git commit --amend

# (check the result)
git show

# (change the commit remotely)
git push --force-with-lease
```

2023-04-11 00:11 UTC, kmk3 reviewed
> ```
> softmaker-common.profile: add fstab to private-etc
> 
> When using `private-etc`, app "forgets" it's product key and
> asks for license activation, despite it has already been done.
> 
> Allow access to "/etc/fstab" to avoid it & related GUI error:
> 
>     The application cannot create a unique identifier.
>     Please make sure the application has sufficient permissions.
> 
> Fixes #5773.
> ```

Nitpick: The wording in the first paragraph is a bit strange; I'd change the
commit message to the following:

```
softmaker-common.profile: add fstab to private-etc

When using `private-etc`, the app "forgets" its product key and
asks for license activation, even though it had already been done.

Allow access to "/etc/fstab" to avoid it & the related GUI error:

    The application cannot create a unique identifier.
    Please make sure the application has sufficient permissions.

Fixes #5773.
```

(It can be amended with the same commands as in [this comment](https://github.com/netblue30/firejail/pull/5777#pullrequestreview-1372905143))

Other than that, LGTM.

2023-04-11 16:59 UTC, hotcapy commented
Done :-)

Sorry about previous text version, I guess in exact such moments it becomes obvious that English isn't one's native language.

2023-04-11 18:40 UTC, merged

2023-04-11 18:40 UTC, kmk3 commented
Merged, thanks!