Update telegram.profile
netblue30/firejail pull request #5994
Opened 2023-09-07 22:51 UTC by mr-tron

new TelegramWebApps use another directory for saving local storage

2023-09-07 23:56 UTC, glitsj16 commented on etc/profile-m-z/telegram.profile
> +noblacklist ${HOME}/.local/share/telegram-desktop
This needs a `blacklist ${HOME}/.local/share/telegram-desktop` counterpart in `disable-programs.inc` to protect the path from leaking into other sandboxes. Respecting alphabetical sorting it should go right after `blacklist ${HOME}/.local/share/swell-foop`.

2023-09-07 23:58 UTC, glitsj16 requested changes
Needs additional blacklisting of the new path in disable-programs.inc. Otherwise fine. Thank you for the PR!

2023-09-08 13:17 UTC, mr-tron commented
added

2023-09-08 13:24 UTC, glitsj16 approved these changes
LGTM

2023-09-09 23:42 UTC, kmk3 approved these changes

2023-09-18 14:15 UTC, merged