profiles: mov-cli: remove ffmpeg & allow more paths
netblue30/firejail pull request #6304
Opened 2024-04-08 09:37 UTC by pirate486743186

Changes:

* Remove ffmpeg from private-bin
* Allow download folder
* It needs an editor to allow editing the config, so I put in nano; sh
  and uname are used for launching nano

2024-04-08 10:37 UTC, glitsj16 commented on etc/profile-m-z/mov-cli.profile
> +private-bin fzf,mov-cli,nano,uname,sh
sorting: private-bin fzf,mov-cli,nano,sh,uname
Probably why checks failed: https://github.com/netblue30/firejail/actions/runs/8597879679/job/23557480018?pr=6304

2024-04-08 10:39 UTC, glitsj16 commented on etc/profile-m-z/mov-cli.profile
> +private-etc X11,alsa,alternatives,asound.conf,ca-certificates,crypto-policies,fonts,group,host.conf,hostname,hosts,ld.so.cache,ld.so.conf,ld.so.conf.d,ld.so.preload,locale,locale.alias,locale.conf,lo
sorting: ...,mime.types,nanorc,nsswitch.conf,...
Probably why checks failed: https://github.com/netblue30/firejail/actions/runs/8597879679/job/23557480018?pr=6304

2024-04-08 10:40 UTC, glitsj16 requested changes
LGTM; needs changes to pass CI sorting checks.

2024-04-09 00:49 UTC, glitsj16 approved these changes

2024-04-09 00:49 UTC, glitsj16 commented
> wait... sort.py is broken? It doesn't actually edit the file, but it tells you the correct edits.

sort.py isn't broken, but there were recent changes you might have missed: https://github.com/netblue30/firejail/commit/aa08aa132bcc48f550fa354c28877753ff2679a3. You'll have to use the `-i` option from now on to write the edits.

2024-04-09 08:07 UTC, kmk3 commented on etc/profile-m-z/mov-cli.profile
> +private-bin fzf,mov-cli,nano,sh,uname
Why remove ffmpeg from private-bin?

2024-04-09 11:44 UTC, kmk3 approved these changes

2024-04-11 04:23 UTC, merged