Add TPM devices to private-dev
netblue30/firejail pull request #6390
Opened 2024-06-22 11:42 UTC by qdii

Add TPM devices to private-dev

Tested locally with:

```
❯ /usr/local/bin/firejail --private-dev --noprofile stat /dev/tpm0
firejail version 0.9.73

Parent pid 34059, child pid 34060
Base filesystem installed in 0.03 ms
Child process initialized in 13.23 ms
  File: /dev/tpm0
  Size: 0         	Blocks: 0          IO Block: 4096   character special file
Device: 0,6	Inode: 150         Links: 1     Device type: 10,224
Access: (0600/crw-------)  Uid: (  973/     tss)   Gid: (  973/     tss)
Access: 2024-06-22 11:20:44.017230197 +0200
Modify: 2024-06-22 11:20:44.017230197 +0200
Change: 2024-06-22 11:20:44.017230197 +0200
 Birth: 2024-06-22 11:20:10.406666659 +0200

Parent is shutting down, bye...
```

2024-06-22 11:49 UTC, rusty-snake reviewed
LGTM

There has to be an follow-up PR that adds notpm to all profiles with private-dev.

2024-06-22 13:12 UTC, qdii commented
@rusty-snake Added a commit that adds `notpm` statement to all the profiles which contain `private-dev`.

2024-06-22 14:51 UTC, glitsj16 approved these changes
LGTM

2024-06-23 06:22 UTC, qdii commented
After this is committed, we should also update the Wiki: https://github.com/netblue30/firejail/wiki/Comparison-of-firejail-and-systemd's-hardening-options

2024-06-23 06:32 UTC, glitsj16 commented on etc/templates/profile.template
> +#notpm
Firejail likes alphabetically ordering options (in profiles). Move it accordingly.

2024-06-23 06:34 UTC, glitsj16 commented on src/man/firejail.1.in
> +.TP
Sort options alphabetically here as well.

2024-06-23 06:35 UTC, glitsj16 commented on src/man/firejail.1.in
> +Use the options --no3d, --nodvd, --nosound, --notv, --notpm, --nou2f and --novideo for additional restrictions.
And one more case of alpha ordering...

2024-06-23 06:36 UTC, glitsj16 approved these changes
LGTM. Some ordering nitpicks...

2024-06-23 06:43 UTC, qdii commented
Amended and force-pushed with alphabetical ordering.

2024-06-23 14:05 UTC, kmk3 requested changes
Sorting.

2024-06-23 14:07 UTC, kmk3 commented
There are some other missing changes:

* [ ] Add `notpm` to profile.c
* [ ] Add `notpm` to firejail-profile.5.in
* [ ] Add `#notpm` to default.profile (keep it commented like `#nou2f` for
  conssitency)
* [ ] Run `make syntax` and commit the resulting changes

See 760f50f78 ("landlock: move commands into profile and add landlock.enforce",
2023-11-17) / PR #6125 for a recent example of a new command.

2024-06-24 21:10 UTC, qdii commented
It looks like force-pushing is making other updates obsolete.
I'm not used to working on `github` just yet, sorry.

2024-06-29 18:34 UTC, kmk3 requested changes
Misc

2024-06-29 18:34 UTC, kmk3 commented on src/firejail/fs_dev.c
> +	{"/dev/tpm0", RUN_DEV_DIR "/tpm0", DEV_TPM},	// Trusted Platform Module devices
```suggestion
	{"/dev/dvb", RUN_DEV_DIR "/dvb", DEV_TV}, // DVB (Digital Video Broadcasting) - TV device
	{"/dev/sr0", RUN_DEV_DIR "/sr0", DEV_DVD}, // for DVD and audio CD players
	{"/dev/tpm0", RUN_DEV_DIR "/tpm0", DEV_TPM}, // TPM (Trusted Platform Module) devices
```

Fix inconsistent whitespace and add "TPM".

2024-06-29 18:34 UTC, kmk3 commented on src/man/firejail-profile.5.in
>  random, snd, urandom, video, log, shm and usb devices are available.
```suggestion
Create a new /dev directory. Only disc, dri, dvb, hidraw, null, full, zero, tty, pts, ptmx,
random, snd, urandom, video, log, shm, tpm and usb devices are available.
```

For consistency with firejail.1.in.

2024-06-29 18:34 UTC, kmk3 commented on src/man/firejail-profile.5.in
> +.TP
```suggestion
\fBnotpm
Disable Trusted Platform Module (TPM) devices.
.TP
```

2024-06-29 18:34 UTC, kmk3 commented on src/man/firejail.1.in
> +Disable TPM devices.
```suggestion
.TP
\fB\-\-notpm
Disable Trusted Platform Module (TPM) devices.
```

2024-07-03 19:31 UTC, qdii commented
> This PR already makes substantial changes by adding the new command; leave the profile changes (other than the ones for default.profile and profile.template) for after this PR to make reviewing easier.

OK, reverted the long list of profile changes. I stored it in another branch to propose later.

> In the parts of the code that are mostly alphabetically sorted (such as in the man pages), it makes sense to put `notpm` before `notv`.
> 
> But in some parts of the code, for whatever reason the multimedia-related options (`nosound`, `noautopulse`, `no3d`, `notv`, `nodvd`) are sorted together, so for consistency put `notpḿ` before `nou2f`, as was suggested in the previous review.
> 
> That is:
> 
> * `notv`, `nou2f` -> `notpm`, `notv`, `nou2f`
> * `nodvd`, `nou2f` -> `nodvd`, `notpm`, `nou2f`

OK, I see.

> Also, avoid sorting things in this PR (especially in the same commit).

This sentence confuses me, because I interpreted the two previous paragraphs as a ask to actually sort these options in a certain way. 

Or do you want to merge this PR, and do the sorting in a different one? I'm happy either way.

> 
> After this PR I might try to make these parts more consistent.

2024-07-04 07:30 UTC, kmk3 commented
> > Also, avoid sorting things in this PR (especially in the same commit).
> 
> This sentence confuses me, because I interpreted the two previous paragraphs
> as a ask to actually sort these options in a certain way.

Sorry, I meant avoid sorting/moving existing lines while adding new lines at
the same time, such as in these cases:

* <https://github.com/netblue30/firejail/pull/6390/commits/6d505558c0587b32727acc6b645bf8e662d250d7#diff-6fcc82b8593aecc46f17f7d9e1a78b3c6e5805730f253f6dc831e046cb82bb6bR40-R43>
* <https://github.com/netblue30/firejail/pull/6390/commits/6d505558c0587b32727acc6b645bf8e662d250d7#diff-e6a16197ececfd99dee7b8ef44752d4b12d39b6787830eec04d2b859be3bf8b4L193-R195>

In general it seems better to avoid refactoring in PRs that just add a new
thing, as they will mostly contain hunks that add new lines, which are easier
to review.  Hunks that sort lines might be wrong/inconsistent with how the
sorting is done elsewhere (this applies to the first link above).

> Or do you want to merge this PR, and do the sorting in a different one? I'm
> happy either way.

I fixed the sorting, squashed the commits, edited the commit message and
force-pushed.

Let me know if there are any issues.

2024-07-04 07:30 UTC, kmk3 approved these changes

2024-07-09 01:43 UTC, merged