profiles: foliate: add foliate to private-bin
netblue30/firejail pull request #6582
Opened 2024-12-27 14:12 UTC by amano-kenji

2024-12-27 17:00 UTC, rusty-snake approved these changes

2024-12-27 17:01 UTC, rusty-snake requested changes
Do we have a profile and a firecfg entry for it?

2024-12-28 04:33 UTC, kmk3 reviewed
As @rusty-snake mentioned, the existing profile should probably be refactored
into a new foliate.profile.

That is:

* Move everything into foliate.profile
* Leave just `private-bin com.github.johnfactotum.Foliate` in
  com.github.johnfactotum.Foliate.profile and make it be a redirect to
  foliate.profile
* Add `private-bin foliate` to foliate.profile
* Add foliate to firecfg.config

Also, please edit the PRs to allow edits/force pushes, as it makes it much
easier to fix misc issues, especially when opening 10 PRs at once:

* <https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork>

2024-12-28 15:52 UTC, kmk3 approved these changes

2025-01-01 14:56 UTC, kmk3 requested changes
Undo these changes:

* https://github.com/netblue30/firejail/compare/0d74058e04441d076c70b31436dec86142443767..1346f0d80058d3a145d715ba33800ef28078e076#diff-0360cc4907b00da8d92fbeedd7eee00c1b3669a28af160fa1a3b93264831cf9c
* https://github.com/netblue30/firejail/compare/0d74058e04441d076c70b31436dec86142443767..1346f0d80058d3a145d715ba33800ef28078e076#diff-276dcb9ef8e39cdf7549c772fbc137b7711be8d6b59fe1edd849b8798971a161

Misc: It looks like the issue was rebasing on master before running just `git
pull --rebase` to get the changes from a few days ago:

* https://github.com/netblue30/firejail/compare/8c85e5593cb70f5c5125dee37737790cc9c74e69..0d74058e04441d076c70b31436dec86142443767

2025-01-06 16:41 UTC, kmk3 approved these changes

2025-01-06 16:42 UTC, merged